name: Build & Push two services to one ECR repo
on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]

env:
  AWS_REGION: ap-south-1
  AWS_ACCOUNT_ID: 818719120332
  ECR_REPO: order-ez

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: user
            svc_dir: user-service
            dockerfile: user-service/Dockerfile
          - name: order
            svc_dir: order-service
            dockerfile: order-service/Dockerfile

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GitHubActionsECRPush
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 新增步骤：清空ECR仓库gcy-app中的所有镜像（只执行一次）
      - name: Clear all images in ECR repo ${{ env.ECR_REPO }}
        if: ${{ matrix.name == 'user' }}  # 仅在第一个matrix实例中执行，避免重复删除
        run: |
          # 列出仓库中所有镜像的ID（包括标签和摘要）
          IMAGE_IDS=$(aws ecr list-images --repository-name ${{ env.ECR_REPO }} --query 'imageIds' --output json)
          
          # 检查是否有镜像需要删除
          if [ "$(echo $IMAGE_IDS | jq '. | length')" -gt 0 ]; then
            echo "Deleting all images in ECR repo ${{ env.ECR_REPO }}..."
            aws ecr batch-delete-image \
              --repository-name ${{ env.ECR_REPO }} \
              --image-ids "$IMAGE_IDS"
            echo "All images deleted successfully."
          else
            echo "ECR repo ${{ env.ECR_REPO }} is already empty. No action needed."
          fi
        shell: bash

      - name: Set tags
        id: vars
        run: |
          echo "SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          if [[ "$GITHUB_REF_TYPE" == "tag" ]]; then
            echo "REF_TAG=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          else
            echo "REF_TAG=latest" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          install: true
          driver-opts: |
            image=moby/buildkit:latest

      - name: Build & Push (${{ matrix.name }}-service)
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./${{ matrix.svc_dir }}
          file: ./${{ matrix.dockerfile }}
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ matrix.name }}-${{ steps.vars.outputs.SHA }}
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ matrix.name }}-${{ steps.vars.outputs.REF_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

